retr0h/gilt

Giltfile.yaml, README.md, examples/go-client/main.go, internal/git.go, internal/git/git.go, internal/git/git_mock.go, internal/git/git_public_test.go, internal/repositories/repositories.go, internal/repositories/repositories_public_test.go, internal/repositories/repositories_test.go, internal/repository/repository.go, internal/repository/repository_public_test.go, pkg/config/schema.go, pkg/config/schema_test.go, pkg/config/types.go, pkg/repositories/repositories.go, test/Giltfile.yaml, test/integration/test_cli.bats
=> Added support to checkout a tag

internal/exec.go, internal/exec/exec.go, internal/exec/exec_mock.go, internal/exec/exec_public_test.go, internal/git.go, internal/git/git.go, internal/git/git_mock.go, internal/git/git_public_test.go, internal/repositories/repositories.go, internal/repositories/repositories_public_test.go, internal/repositories/repositories_test.go, internal/repository.go, internal/repository/repository.go, internal/repository/repository_mock.go, internal/repository/repository_public_test.go, test/integration/test_cli.bats
- Clone repositories into the cache with `--bare` to keep just the repo objects in cache, rather than an unused copy of the working tree.  This can yield a significant space savings in repositories with large numbers of files
- Clone repositories into the cache with `--filter=blob:none`.  This will skip downloading any objects from the repository in the initial copy of the clone, and only populate the repository metadata; subsequent operations will automatically download the required objects (and ONLY the required objects) from origin as needed.  This yields a massive space/performance boost.
- Make use of the `git worktree` subcommand to populate `dstDir` targets rather than `git checkout-index`.  This subcommand is designed for using a single repository as a source for multiple copies …
=> fix: Refactor cloning and caching workflow

Giltfile.yaml, docs/docs/configuration.md, docs/docs/usage.md, examples/go-client/go.mod, examples/go-client/go.sum, examples/go-client/main.go, internal/git/git_public_test.go, internal/repositories/repositories_public_test.go, internal/repository/repository.go, internal/repository/repository_public_test.go, pkg/config/schema.go, pkg/config/schema_test.go, pkg/config/types.go, pkg/repositories/repositories.go, test/Giltfile.yaml
Commit d306437a045ae878a85d249282dbc838ce2ada77 made the handling of these two fields 100% equivalent.
Breaking change will need to migrate `Giltfile.yaml` `repositories.tag` and/or `repositories.sha` to `repositories.version`
From:
```yaml
repositories:
- git: https://github.com/retr0h/ansible-etcd.git
sha: 77a95b7
dstDir: /tmp/retr0h.ansible-etcd
- git: https://github.com/retr0h/ansible-etcd.git
tag: 1.1
dstDir: /tmp/retr0h.ansible-etcd-tag
```
To:
```yaml
repositories:
- git: https://github.com/retr0h/ansible-etcd.git
version: 77a95b7
dstDir: /tmp/retr0h.ansible-etcd
- git: https://github.com/retr0h/ansible-etcd.git
version: 1.1
dstDir: /tmp/retr0h.ansible-etcd-tag
```
Fixes: #74
=> feat: merge tag and sha fields into version

internal/repository/repository.go, internal/repository/repository_public_test.go, test/integration/test_cli.bats
Commit d306437a045ae878a85d249282dbc838ce2ada77 pulled out the name normalization for cache directories and left it up to the tooling to work it out; turns out the tooling is preposterously bad at it, and shouldn't be trusted.
Restore the needed functionality, and keep cached copies in properly-namespaced locations under the hood.
Fixes: Issue #100
=> fix: Restore proper namespace separation of cached clones

pkg/config/schema_test.go
We have an entrypoint for validating the Repositories schema, so use it when validating, to ensure test coverage.  All the other tests will use the validator in the test suite.
Fixes: Issue #106
=> refactor: Get config.Validate() under test

go.mod, internal/exec/exec.go, internal/exec/exec_public_test.go, internal/exec/types.go, internal/git/git.go, internal/git/git_public_test.go, internal/git/types.go, internal/repositories/repositories.go, pkg/repositories/repositories.go
When running post-commands, log both the command and all defined args, to aid troubleshooting.
chore: correct a typo that was gumming up the Go Report Card
refactor: remove unused `debug` attribute from managers
This appears to be a vestigial; there's a logger object available everywhere, and checking the log level is easier than setting this flag everywhere
=> fix: log the entire post-command being run

cmd/root.go
Re-initialize the logger after the config file is loaded, to pick up any new values.
Fixes: Issue #114
=> fix: enable debug output via `debug: true` in the config file

cmd/init.go, cmd/overlay.go, cmd/root.go, test/integration/test_cli.bats
Cleanup the excessive calls to initLogger().  This is only marginally better.
=> chore: refactor initLogger()

cmd/root.go
No need to create another log instance, simply change the log level once config is loaded.
=> chore: additional initLogger cleanup

.goreleaser.yaml, Taskfile.yml, python/dist2wheel.py
Adds a `build` sub-target called `build:wheel`, that will assemble Python wheels for all artifacts built under `dist/`, according to the PEP 491 specification.
The script does the absolute bare minimum to generate a package that will allow `pip install` and `pip uninstall` to place the gilt binary under `bin/`, using packages that should be entirely available via the Python stdlib.  i.e., a minimalist Python runtime should be able to do the work, with no venv or anything required.
It does not make sdists.
It does not upload to PyPI.
Tested on Debian 12, Alpine 3.16, Mac OS X 10.15, and macOS 14.2, all x86_64.  ARM builds were not tested for lack of hardware.
Drive-by: change the name of the Goreleaser `name_template` so that snapshot builds will make/use version numbers that are …
=> feat: add a `build:wheel` task to Taskfile.yml

python/dist2wheel.py
Verified installs on Ubuntu Jammy and Alpine 3.19 (aarch64)
=> chore: add support for packaging Linux ARM64 wheels

python/dist2wheel.py
Verified install on an Apple M2 running 14.3
=> chore: add support for packaging macOS ARM64 wheels

.goreleaser.yaml, python/dist2wheel.py
It's twice the size, but it makes distribution SO much simpler.
=> chore: build Universal binaries for OSX

internal/git.go, internal/git/git.go, internal/git/git_public_test.go, internal/mocks/git/git_mock.go, internal/repository/repository.go, internal/repository/repository_public_test.go
Special care and handling is needed to keep tags up-to-date with the remote; all other assets seem to be fetched/updated as needed.
Fixes: Issue #142
=> fix: fetch current tags from remote on clone cache hit

internal/repositories/repositories.go, internal/repositories/repositories_public_test.go, internal/repository/copy.go, pkg/repositories/repositories.go, test/integration/test_cli.bats
Redo the order-of-operations so that the destination file is nominally non-readable, and does not attempt to create the file until all info about the source file is in-hand.
Fixes: Issue #149
=> refactor: attempt to make `CopyFile` more secure

examples/go-client/go.mod, examples/go-client/go.sum, go.mod, go.sum, internal/exec/exec.go, internal/exec/exec_public_test.go, internal/exec/types.go, internal/git/git.go, internal/git/git_public_test.go, internal/git/types.go, internal/repositories/repositories.go, internal/repositories/repositories_public_test.go, internal/repositories/repositories_test.go, internal/repositories/types.go, internal/repository/copy.go, internal/repository/copy_public_test.go, internal/repository/helper_test.go, internal/repository/repository.go, internal/repository/repository_public_test.go, internal/repository/types.go, pkg/repositories/repositories.go, pkg/repositories/types.go
[avfs](https://github.com/avfs/avfs) does the same thing as afero, but provides a more complete abstraction layer, and a more fully-functional MemFS for testing, i.e., it supports symlinks.
Move all file operations over to avfs, including `exec.RunInTempDir`, and add unit tests for symlink handling.
=> refactor: replace afero with avfs

internal/git/git_public_test.go, internal/repositories/repositories_public_test.go, internal/repositories/repositories_test.go, internal/repository/repository_public_test.go
Call `gomock.Controller.Finish` at the end of `TearDownTest`, not `SetupTest`.  Clean up tests with useless mocks that never got called (which is now, rightly, an error)
=> test: Do a proper test teardown

Taskfile.yml, internal/git/git.go, internal/git/git_public_test.go, internal/mocks/vfs/failfs.go, internal/mocks/vfs/failfs_test.go, internal/repository/copy_public_test.go
Adds FailFS, which is an AVFS-compatible filesystem that will overlay another, and can run user-supplied functions over the various calls.
Use this to create filesystem mocks that simulate various failures to ensure that all code paths are behaving as expected.
=> chore: get coverage to 100%

internal/repository/copy.go, internal/repository/copy_public_test.go
Clean up all the unit tests that were creating the target dir in order to pass.
Fixes: Issue #173
=> fix: make `sources.dstFile` create parent dirs

internal/mocks/vfs/failfs.go, internal/repository/copy.go, internal/repository/copy_public_test.go, internal/repository/repository.go
Use the already-open file descriptors for reading/writing metadata, rather than the long-form VFS versions.
Add/use FailFS fixtures as needed.
=> refactor: use the File methods for Stat, Chmod

.goreleaser.yaml
`brews.folder` was renamed to `brews.directory` in goreleaser 1.25
=> chore: stop using deprecated values w/ goreleaser

.github/delete-merged-branch-config.yml
Allow dependabot to delete it's own branches.
=> ci: preserve dependabot branches

.github/workflows/go.yml, .golangci.yml, Taskfile.yml, examples/go-client/go.mod, go.mod
* Switched to go 1.22 and execute coverage with nocoverageredesign which seems to correct some buggy coverage reporting
* Also pinned deps to @latest from arbitrary versions
* Updated deprecated golangci config `run.skip-dirs`
* go mod tidy
* go install golangci-lint
Fixes: #179
=> Switch to go 1.22

python/dist2wheel.py
Allow `dist2wheel.py` to better handle missing extra field on the internal goreleaser build artifact.
Fixes: #193
=> fix: allow dist2wheel to handle missing field

pkg/repositories/repositories.go, test/integration/test_cli.bats
Block on acquiring the global lock, rather than aborting.
Fixes: Issue #202
=> fix: wait for the lockfile on startup

Taskfile.yml
At least in the case of Debian Bookworm, the Go 1.22.3 runtime on Linux builds Gilt just fine.  It can even cross-compile working Universal binaries for Darwin.
Quit drinking the haterade and lying when asked if it's a supported environment.
=> fix: quit claiming Linux is an unsupported dev environment

internal/repository/copy.go, internal/repository/copy_public_test.go
Traversal bits (aka, x-bits) on directories are occasionally useful. Make sure they are set when creating target dirs.
Fixes: Issue #214
=> fix: make CopyFile create target directories with sensible permissions

docs/docs/configuration.md
Provide an explicit command reference for the `Giltfile.yaml`, all environment variables, and command-line switches.
Fixes: Issue #217
=> docs: fill out the `configuration.md`

examples/go-client/go.mod, examples/go-client/go.sum, internal/git/git.go, internal/git/git_public_test.go
commit 21f7c3ff04247af578f78162e5040a0423d3d565 uses a `git` invocation that only works on Git 2.39 or newer; replace it with a more backward-compatible command that should work on older versions of Git.
Fixes: Issue #218
=> fix: use a backwards-compatible command for setting the remote name

docs/docs/configuration.md, pkg/config/schema_test.go, pkg/config/types.go
The overlay code calls `RemoveAll` on existing target directories, which absolutely does not work when the target directory is the current or parent directory.  Check for this when validating the config file, so it can fail-fast.
Update docs to explicitly admonish people trying to do this.
Fixes: Issue #228
=> fix: disallow `.` and `..` for `dstDir`

Taskfile.yml
Not entirely sure why I had setup go-junit-report as gocover-cobertura does what we want.
=> ci: no reason to use go-junit-report

go.mod
Will upgrade to go 1.24 at a later date.
* actions/setup-go@v5 installs Go 1.23
* one of the dependencies declares go 1.24 or higher
* starting in Go 1.21, the go command can auto-download a newer Go version if needed to match the declared version
* when a build runs, Go detects the mismatch and downloads & switches to Go 1.24.1
* this causes golangci-lint (built with Go 1.23) to fail
=> fix: pin go toolchain to 1.23
